### PR TITLE
Add aur package

### PR DESCRIPTION
**Pull request by AriaMoradi**
Hey, I made a package for Arch Linux. This would let people know about it.

### CODE REVIEW

**Review by Visne — APPROVED** [review]
Hi there, thanks for maintaining this AUR package.

I've added a warning that this package is not "official", and I've added a command for `paru` (I put paru above yay, as it always shows PKGBUILDs/diffs which I consider to be safer for users).

If possible it would be great if the AUR package also contained a `.desktop` file, but I guess there is not really a square icon for RSIEdit. Regardless, it's not directly relevant to this PR.

**Comment by Visne** [comment]
> there is not really a square icon for RSIEdit

Well, currently it just uses the SS14 icon. You could use that if you like.

**Comment by AriaMoradi** [comment]
> I've added a warning that this package is not "official", and I've added a command for paru (I put paru above yay, as it always shows PKGBUILDs/diffs which I consider to be safer for users).

Being unofficial and the need to review PKGBUILDS in the AUR is part of what how it works, but still good to warn about it.

> If possible it would be great if the AUR package also contained a .desktop file, but I guess there is not really a square icon for RSIEdit. Regardless, it's not directly relevant to this PR.

I can try to make a desktop file if we require it? I think that it's not necessary as this is a minor tool

**Comment by Visne** [comment]
> I think that it's not necessary as this is a minor tool

It's a GUI tool nonetheless, so having a button in your start menu is preferable over having to run it from the terminal.

**Comment by AriaMoradi** [comment]
Updated the package, now it includes a desktop entry with an icon

**Comment by Visne** [comment]
Thanks!

**Pull request merged**
